extends: default

rules:
  empty-lines:
    max: 1
    max-start: 0
    max-end: 1

  indentation:
    spaces: 2
    indent-sequences: consistent

  line-length:
    max: 120

  comments:
    min-spaces-from-content: 1

  truthy: disable
