extends: default

rules:
  new-line-at-end-of-file: disable
  new-line-at-end-of-file: disable
  trailing-spaces: disable

  empty-lines:
    max: 2
    max-start: 0
    max-end: 2

  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  line-length:
    max: 120

  comments:
    min-spaces-from-content: 1

  truthy: disable

