apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cache
  namespace: geoserver
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 200Gi
      

