apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: geoserver
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 500Gi