apiVersion: v1
kind: Service
metadata:
  name: geoserver-service
  namespace: geoserver
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  selector:
    app: geoserver
  type: LoadBalancer
  loadBalancerIP: 10.10.0.1 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 

