apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-secrets
  namespace: pgbouncer
type: Opaque
stringData:
  DB_PASSWORD: CHANGE-ME
  DB_USER: CHANGE-ME
  DB_NAME: database
  DB_HOST: 10.10.0.10:5432 #Example

