apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  name: pgbouncer-service
  namespace: pgbouncer
spec:
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      protocol: TCP
      port: 6432
      targetPort: 6432
  type: LoadBalancer
  loadBalancerIP: 10.10.0.3

