apiVersion: v1
kind: Service
metadata:
  name: haproxy-k3s-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.1.1 # Example 
  ports:
  - name: api
    port: 16443
    targetPort: 6443
    protocol: TCP
  - name: stats
    port: 8404
    targetPort: 8404
    protocol: TCP
  selector:
    app: haproxy-k3s

